/*
 * Copyright 2013-present febit.org (support@febit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.febit.common.jooq;

import org.febit.common.jooq.foo.FooPO;
import org.febit.common.jooq.foo.FooRecord;
import org.febit.common.jooq.foo.FooStatus;
import org.febit.common.jooq.foo.FooTestSupport;
import org.febit.common.jooq.foo.TFoo;
import org.jooq.Configuration;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class IInsertDaoTest {

    static class FooInsertDao extends BaseDao<TFoo, FooPO, FooRecord>
            implements IInsertDao<TFoo, FooPO, Long, FooRecord> {

        public FooInsertDao(Configuration conf) {
            super(conf);
        }
    }

    @Nested
    class Foo extends FooTestSupport {
        private final FooInsertDao dao = new FooInsertDao(conf());

        @Test
        void single() {
            dao.insert(foo("Alice"));
            assertThat(crud().listAll()).hasSize(1);
        }

        @Test
        void multiple() {
            dao.insert(foo("Alice"), foo("Bob"));
            assertThat(crud().listAll()).hasSize(2);
        }

        @Test
        void emptyCollection() {
            dao.insert(List.of());
            assertThat(crud().listAll()).isEmpty();
        }

        @Test
        void singleCollection() {
            dao.insert(List.of(foo("Alice")));
            assertThat(crud().listAll()).hasSize(1);
        }

        @Test
        void multipleCollection() {
            dao.insert(List.of(foo("Alice"), foo("Bob")));
            assertThat(crud().listAll()).hasSize(2);
        }

        @Test
        void withEnumStatus() {
            dao.insert(foo("Alice", FooStatus.RUNNING));
            var all = crud().listAll();
            assertThat(all.getFirst().getStatus()).isEqualTo(FooStatus.RUNNING);
        }

        @Test
        void withJsonBean() {
            dao.insert(foo("JsonUser"));
            var stored = crud().requireFirst();
            assertThat(stored.getJsonVarchar()).isNotNull();
            assertThat(stored.getJsonVarchar().getName()).isEqualTo("j-JsonUser");
            assertThat(stored.getJsonText().getTitle()).isEqualTo("t-JsonUser");
        }

        @Test
        void withJsonStringConverters() {
            dao.insert(foo("JsonStr"));
            var stored = crud().requireFirst();
            assertThat(stored.getStringJsonBean().getName()).isEqualTo("j-JsonStr");
            assertThat(stored.getStringJsonBeanArray()).hasSize(1);
            assertThat(stored.getStringJsonBeanList()).hasSize(1);
            assertThat(stored.getStringJsonBeanMap()).containsKey(1);
            assertThat(stored.getStringJsonMap()).containsEntry(1, true);
        }

        @Test
        void timestampsAreAutoGenerated() {
            dao.insert(foo("Ts"));
            var stored = crud().requireFirst();
            assertThat(stored.getCreatedAt()).isNotNull();
            assertThat(stored.getUpdatedAt()).isNotNull();
        }

        @Test
        void insertBuilder() {
            dao.insert()
                    .set(dao.table().NAME, "Builder")
                    .set(dao.table().STATUS, FooStatus.CREATED)
                    .execute();
            var stored = crud().requireFirst();
            assertThat(stored.getName()).isEqualTo("Builder");
            assertThat(stored.getStatus()).isEqualTo(FooStatus.CREATED);
        }

        @Test
        void batchInsertWhenReturnRecordToPojoDisabled() {
            var batchConf = conf().derive(conf().settings()
                    .withReturnRecordToPojo(false));
            var batchDao = new FooInsertDao(batchConf);

            batchDao.insert(List.of(foo("Alice"), foo("Bob")));

            assertThat(crud().listAll()).hasSize(2);
            assertThat(crud().listFieldBy(dao.table().NAME))
                    .containsExactlyInAnyOrder("Alice", "Bob");
        }
    }

}
